[package]
name = "craftsec-node"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
craftsec-core = { workspace = true }
craftsec-dkg = { workspace = true }
craftsec-signing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ed25519-dalek = { workspace = true }
curve25519-dalek = { workspace = true }
